### ISSUE TITLE
TypeError: Object 10 has no method 'replace'

### ISSUE THREAD

**Issue by jamc** [dylang/npm-check#13] opened 2015-02-20 02:36 UTC
Hey! Great module before all!

Now, I'm getting this error:
```
jam$ npm-check

/usr/local/lib/node_modules/npm-check/node_modules/depcheck/index.js:54
          return module.replace(/\/.*$/, '');
                        ^
TypeError: Object 10 has no method 'replace'
    at /usr/local/lib/node_modules/npm-check/node_modules/depcheck/index.js:54:25
    at Array.map (native)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm-check/node_modules/depcheck/index.js:53:43)
    at EventEmitter.emit (events.js:106:17)
    at fn (/usr/local/lib/node_modules/npm-check/node_modules/depcheck/node_modules/walkdir/walkdir.js:82:19)
    at Object.oncomplete (fs.js:107:15)
```

It only happens with `npm-check`, if I run `npm-check -u` it works well.

Can you help me please?

**Comment by dylang** [comment] 2015-02-23 02:54
The bug is in the module `npm-check` uses to check for unused modules. Use `--skip-unused` (or `-s`) to avoid it.

Can you tell me more about the project? Is it open source? Are you using `require` statements in non-Node code, such as using browserify, or using an ES6 transplier? There's nothing wrong with these, I just want an idea of what to look for to fix this.

**Comment by jamc** [comment] 2015-02-23 13:50
Thanks for the response, the project is not open source but one peculiar thing is that it has private git repositories as modules:

```json
"dependencies": {
    "async": "^0.9.0",
    "body-parser": "^1.12.0",
    "cors": "^2.5.3",
    "express": "^4.11.2",
    "lodash": "^3.3.0",
    "q": "^1.1.2",
    "private-module": "git+ssh://git@github.com:user/git-repo.git#v0.1.0",
    "private-module2": "git+ssh://git@github.com:user/git-repo2.git#v0.1.0",
    "private-module3": "git+ssh://git@github.com:user/git-repo3.git#v0.1.0",
    "private-module4": "git+ssh://git@github.com:user/git-repo4.git#v0.1.0"
  },
  "devDependencies": {
    "airbrake": "^0.3.8",
    "blanket": "^1.1.6",
    "chai": "^2.0.0",
    "grunt": "^0.4.5",
    "grunt-cli": "^0.1.13",
    "mocha": "^2.1.0",
    "mockery": "git+ssh://git@github.com:jamc/mockery.git",
    "nock": "^0.59.1",
    "nock-exec": "^0.1.0",
    "redis": "^0.12.1",
    "redis-mock": "^0.4.4",
    "request": "^2.53.0",
    "sinon": "^1.12.2"
  }
```

In other projects, `npm-check` just shows an error saying that could not find these modules, it's only in this particular project where it crashes.

In the json above are the exact modules that i use, i just removed the privates ones (13 private modules).

Let me know if i can help on this.

Cheers!

**Comment by dylang** [comment] 2015-02-24 19:46
I've made a PR for depcheck that should fix this: https://github.com/rumpl/depcheck/pull/20

I don't think the problem is related to using modules off github.

You can run your own npm repo, it can make version mangling much easier because you can use semver.  If setting up couchdb seems daunting, I was playing with https://github.com/rlidwka/sinopia over the weekend and it was easy to configure and run.

**Comment by dylang** [comment] 2015-02-28 20:01
My PR was merged, if you `npm -g i npm-check` you should get the new version with this fix. I'm going to close this ticket but let me know if you still have the problem and I'll re-open.

**Closed by dylang** 2015-02-28 20:01 UTC

**Comment by jamc** [comment] 2015-03-02 14:07
It's working perfect now, thank you!
