### ISSUE TITLE
*react-redux and *classnames package bug

### ISSUE THREAD

**Issue by js08** [dylang/npm-check#54] opened 2015-10-21 15:13 UTC
Hi,

We have tested the npm-check package with a sample todo react app, but its not recognizing the *react-redux and *classnames package. We are using the npm version : 2.11.3 and node version: v0.12.7.

You can see in the code where they have used react-redux and classnames packages
https://github.com/rackt/redux/blob/master/examples/todomvc/containers/App.js
import { connect } from 'react-redux';

https://github.com/rackt/redux/blob/master/examples/todomvc/components/TodoTextInput.js
import classnames from 'classnames';

Providing the output below

npm-check
---------

D:\todomvc>npm-check

classnames           ?  NOTUSED?  Possibly never referenced in the code.
                                  npm uninstall --save classnames to remove.
                     ??  NPM ERR!  Registry error connect ETIMEDOUT

react                ??  NPM ERR!  Registry error connect ETIMEDOUT

react-redux          ?  NOTUSED?  Possibly never referenced in the code.
                                  npm uninstall --save react-redux to remove.
                     ??  NPM ERR!  Registry error connect ETIMEDOUT

redux                ??  NPM ERR!  Registry error connect ETIMEDOUT

raw-loader           ?  NOTUSED?  Possibly never referenced in the code.
                                  npm uninstall --save-dev raw-loader to remove.
                     ??  NPM ERR!  Registry error connect ETIMEDOUT

babel-core           ??  NPM ERR!  Registry error connect ETIMEDOUT

jsdom                ?  NOTUSED?  Possibly never referenced in the code.
                                  npm uninstall --save-dev jsdom to remove.
                     ??  NPM ERR!  Registry error connect ETIMEDOUT

mocha-jsdom          ??  NPM ERR!  Registry error connect ETIMEDOUT

babel-loader         ?  NOTUSED?  Possibly never referenced in the code.
                                  npm uninstall --save-dev babel-loader to remove.
                     ??  NPM ERR!  Registry error connect ETIMEDOUT

mocha                ??  NPM ERR!  Registry error connect ETIMEDOUT

expect               ??  NPM ERR!  Registry error connect ETIMEDOUT

node-libs-browser    ?  NOTUSED?  Possibly never referenced in the code.
                                  npm uninstall --save-dev node-libs-browser to remove.
                     ??  NPM ERR!  Registry error connect ETIMEDOUT

react-hot-loader     ?  NOTUSED?  Possibly never referenced in the code.
                                  npm uninstall --save-dev react-hot-loader to remove.
                     ??  NPM ERR!  Registry error connect ETIMEDOUT

style-loader         ?  NOTUSED?  Possibly never referenced in the code.
                                  npm uninstall --save-dev style-loader to remove.
                     ??  NPM ERR!  Registry error connect ETIMEDOUT

todomvc-app-css      ?  NOTUSED?  Possibly never referenced in the code.
                                  npm uninstall --save-dev todomvc-app-css to remove.
                     ??  NPM ERR!  Registry error connect ETIMEDOUT

webpack              ??  NPM ERR!  Registry error connect ETIMEDOUT

webpack-dev-server   ??  NPM ERR!  Registry error connect ETIMEDOUT

**Comment by js08** [comment] 2015-10-22 15:07
can you some one please reply

**Comment by dylang** [comment] 2015-10-22 20:11
Hi @JS08. Please understand I'm working on this module as a side project for my own enjoyment when I have free time. I have a full time job, two young kids, and other responsibilities. I'm lucky if I have the time and energy to work on my open source projects once or twice a week, so I'm not always able to reply to issues right away. My situation is not special or unique, many open source developers are doing the work they are doing for fun and in what little spare time they have.

I hope to help you with your issue but please be patient as I don't have time right now.

Interesting issue. Can you share some information:

```
npm config get prefix
```

```
which npm-check
```

```
npm-check --version
```

```
npm-check -g --debug
```

That last one will be long, you can do 

```
npm-check -g --debug | pbcopy
```

to put it in your clipboard and then paste it here. Also, please read the Markdown documentation to learn how to make the `text you are pasting here look like this`, it will make reading your messages much easier. 

Thank you!

**Comment by js08** [comment] 2015-10-22 20:55
@dylang thanks for your reply, we are using the latest version

**Comment by js08** [comment] 2015-10-23 02:51
Providing the output below
![screen shot 2015-10-22 at 9 26 53 pm](https://cloud.githubusercontent.com/assets/1699943/10683108/a6748420-7903-11e5-8bca-5dc1c9ec5dec.png)

we are using npm 4.1.2

npm-check --debug
```
{ options: 
   { update: undefined,
     global: undefined,
     skipUnused: undefined,
     ignoreDev: undefined,
     debug: true,
     path: '/Users/Raj/Desktop/FrontEnd/redux-master/examples/todomvc' } }
{ classnames: 
   { moduleName: 'classnames',
     homepage: 'https://github.com/JedWatson/classnames#readme',
     error: undefined,
     latest: '2.2.0',
     installed: '2.2.0',
     isInstalled: '2.2.0',
     notInstalled: false,
     packageWanted: '2.2.0',
     packageJson: '^2.1.2',
     isPrivate: undefined,
     devDependency: false,
     usedInScripts: undefined,
     mismatch: false,
     semverValidRange: '>=2.1.2 <3.0.0',
     semverValid: '2.2.0',
     easyUpgrade: true,
     bump: null,
     unused: true },
  react: 
   { moduleName: 'react',
     homepage: 'https://github.com/facebook/react/tree/master/npm-react',
     error: undefined,
     latest: '0.14.0',
     installed: '0.14.0',
     isInstalled: '0.14.0',
     notInstalled: false,
     packageWanted: '0.14.0',
     packageJson: '^0.14.0',
     isPrivate: undefined,
     devDependency: false,
     usedInScripts: undefined,
     mismatch: false,
     semverValidRange: '>=0.14.0 <0.15.0',
     semverValid: '0.14.0',
     easyUpgrade: true,
     bump: null,
     unused: true },
  'react-dom': 
   { moduleName: 'react-dom',
     homepage: 'https://github.com/facebook/react/tree/master/npm-react-dom',
     error: undefined,
     latest: '0.14.0',
     installed: '0.14.0',
     isInstalled: '0.14.0',
     notInstalled: false,
     packageWanted: '0.14.0',
     packageJson: '^0.14.0',
     isPrivate: undefined,
     devDependency: false,
     usedInScripts: undefined,
     mismatch: false,
     semverValidRange: '>=0.14.0 <0.15.0',
     semverValid: '0.14.0',
     easyUpgrade: true,
     bump: null,
     unused: true },
  'react-redux': 
   { moduleName: 'react-redux',
     homepage: 'https://github.com/gaearon/react-redux',
     error: undefined,
     latest: '4.0.0',
     installed: '4.0.0',
     isInstalled: '4.0.0',
     notInstalled: false,
     packageWanted: '4.0.0',
     packageJson: '^4.0.0',
     isPrivate: undefined,
     devDependency: false,
     usedInScripts: undefined,
     mismatch: false,
     semverValidRange: '>=4.0.0 <5.0.0',
     semverValid: '4.0.0',
     easyUpgrade: true,
     bump: null,
     unused: true },
  redux: 
   { moduleName: 'redux',
     homepage: 'http://rackt.github.io/redux',
     error: undefined,
     latest: '3.0.3',
     installed: '3.0.3',
     isInstalled: '3.0.3',
     notInstalled: false,
     packageWanted: '3.0.3',
     packageJson: '^3.0.0',
     isPrivate: undefined,
     devDependency: false,
     usedInScripts: undefined,
     mismatch: false,
     semverValidRange: '>=3.0.0 <4.0.0',
     semverValid: '3.0.3',
     easyUpgrade: true,
     bump: null,
     unused: false },
  'babel-core': 
   { moduleName: 'babel-core',
     homepage: 'https://babeljs.io/',
     error: undefined,
     latest: '5.8.25',
     installed: '5.8.25',
     isInstalled: '5.8.25',
     notInstalled: false,
     packageWanted: '5.8.25',
     packageJson: '^5.6.18',
     isPrivate: undefined,
     devDependency: true,
     usedInScripts: 'test',
     mismatch: false,
     semverValidRange: '>=5.6.18 <6.0.0',
     semverValid: '5.8.25',
     easyUpgrade: true,
     bump: null,
     unused: false },
  expect: 
   { moduleName: 'expect',
     homepage: 'https://github.com/mjackson/expect',
     error: undefined,
     latest: '1.12.2',
     installed: '1.12.2',
     isInstalled: '1.12.2',
     notInstalled: false,
     packageWanted: '1.12.2',
     packageJson: '^1.8.0',
     isPrivate: undefined,
     devDependency: true,
     usedInScripts: undefined,
     mismatch: false,
     semverValidRange: '>=1.8.0 <2.0.0',
     semverValid: '1.12.2',
     easyUpgrade: true,
     bump: null,
     unused: false },
  jsdom: 
   { moduleName: 'jsdom',
     homepage: 'https://github.com/tmpvar/jsdom#readme',
     error: undefined,
     latest: '7.0.2',
     installed: '5.6.1',
     isInstalled: '5.6.1',
     notInstalled: false,
     packageWanted: '5.6.1',
     packageJson: '^5.6.1',
     isPrivate: undefined,
     devDependency: true,
     usedInScripts: undefined,
     mismatch: false,
     semverValidRange: '>=5.6.1 <6.0.0',
     semverValid: '5.6.1',
     easyUpgrade: false,
     bump: 'major',
     unused: false },
  'babel-plugin-react-transform': 
   { moduleName: 'babel-plugin-react-transform',
     homepage: 'https://github.com/gaearon/babel-plugin-react-transform#readme',
     error: undefined,
     latest: '1.1.1',
     installed: '1.1.1',
     isInstalled: '1.1.1',
     notInstalled: false,
     packageWanted: '1.1.1',
     packageJson: '^1.1.0',
     isPrivate: undefined,
     devDependency: true,
     usedInScripts: undefined,
     mismatch: false,
     semverValidRange: '>=1.1.0 <2.0.0',
     semverValid: '1.1.1',
     easyUpgrade: true,
     bump: null,
     unused: true },
  express: 
   { moduleName: 'express',
     homepage: 'http://expressjs.com/',
     error: undefined,
     latest: '4.13.3',
     installed: '4.13.3',
     isInstalled: '4.13.3',
     notInstalled: false,
     packageWanted: '4.13.3',
     packageJson: '^4.13.3',
     isPrivate: undefined,
     devDependency: true,
     usedInScripts: undefined,
     mismatch: false,
     semverValidRange: '>=4.13.3 <5.0.0',
     semverValid: '4.13.3',
     easyUpgrade: true,
     bump: null,
     unused: true },
  'babel-loader': 
   { moduleName: 'babel-loader',
     homepage: 'https://github.com/babel/babel-loader',
     error: undefined,
     latest: '5.3.2',
     installed: '5.3.2',
     isInstalled: '5.3.2',
     notInstalled: false,
     packageWanted: '5.3.2',
     packageJson: '^5.1.4',
     isPrivate: undefined,
     devDependency: true,
     usedInScripts: undefined,
     mismatch: false,
     semverValidRange: '>=5.1.4 <6.0.0',
     semverValid: '5.3.2',
     easyUpgrade: true,
     bump: null,
     unused: true },
  mocha: 
   { moduleName: 'mocha',
     homepage: 'https://github.com/mochajs/mocha#readme',
     error: undefined,
     latest: '2.3.3',
     installed: '2.3.3',
     isInstalled: '2.3.3',
     notInstalled: false,
     packageWanted: '2.3.3',
     packageJson: '^2.2.5',
     isPrivate: undefined,
     devDependency: true,
     usedInScripts: 'test',
     mismatch: false,
     semverValidRange: '>=2.2.5 <3.0.0',
     semverValid: '2.3.3',
     easyUpgrade: true,
     bump: null,
     unused: false },
  'node-libs-browser': 
   { moduleName: 'node-libs-browser',
     homepage: 'http://github.com/webpack/node-libs-browser',
     error: undefined,
     latest: '0.5.3',
     installed: '0.5.3',
     isInstalled: '0.5.3',
     notInstalled: false,
     packageWanted: '0.5.3',
     packageJson: '^0.5.2',
     isPrivate: undefined,
     devDependency: true,
     usedInScripts: undefined,
     mismatch: false,
     semverValidRange: '>=0.5.2 <0.6.0',
     semverValid: '0.5.3',
     easyUpgrade: true,
     bump: null,
     unused: true },
  'raw-loader': 
   { moduleName: 'raw-loader',
     homepage: 'https://github.com/webpack/raw-loader',
     error: undefined,
     latest: '0.5.1',
     installed: '0.5.1',
     isInstalled: '0.5.1',
     notInstalled: false,
     packageWanted: '0.5.1',
     packageJson: '^0.5.1',
     isPrivate: undefined,
     devDependency: true,
     usedInScripts: undefined,
     mismatch: false,
     semverValidRange: '>=0.5.1 <0.6.0',
     semverValid: '0.5.1',
     easyUpgrade: true,
     bump: null,
     unused: true },
  'react-addons-test-utils': 
   { moduleName: 'react-addons-test-utils',
     homepage: undefined,
     error: undefined,
     latest: '0.14.0',
     installed: '0.14.0',
     isInstalled: '0.14.0',
     notInstalled: false,
     packageWanted: '0.14.0',
     packageJson: '^0.14.0',
     isPrivate: undefined,
     devDependency: true,
     usedInScripts: undefined,
     mismatch: false,
     semverValidRange: '>=0.14.0 <0.15.0',
     semverValid: '0.14.0',
     easyUpgrade: true,
     bump: null,
     unused: true },
  'react-transform-hmr': 
   { moduleName: 'react-transform-hmr',
     homepage: 'https://github.com/gaearon/react-transform-hmr#readme',
     error: undefined,
     latest: '1.0.1',
     installed: '1.0.1',
     isInstalled: '1.0.1',
     notInstalled: false,
     packageWanted: '1.0.1',
     packageJson: '^1.0.0',
     isPrivate: undefined,
     devDependency: true,
     usedInScripts: undefined,
     mismatch: false,
     semverValidRange: '>=1.0.0 <2.0.0',
     semverValid: '1.0.1',
     easyUpgrade: true,
     bump: null,
     unused: true },
  'style-loader': 
   { moduleName: 'style-loader',
     homepage: 'https://github.com/webpack/style-loader#readme',
     error: undefined,
     latest: '0.13.0',
     installed: '0.12.4',
     isInstalled: '0.12.4',
     notInstalled: false,
     packageWanted: '0.12.4',
     packageJson: '^0.12.3',
     isPrivate: undefined,
     devDependency: true,
     usedInScripts: undefined,
     mismatch: false,
     semverValidRange: '>=0.12.3 <0.13.0',
     semverValid: '0.12.4',
     easyUpgrade: false,
     bump: 'nonSemver',
     unused: true },
  'todomvc-app-css': 
   { moduleName: 'todomvc-app-css',
     homepage: 'https://github.com/tastejs/todomvc-app-css',
     error: undefined,
     latest: '2.0.1',
     installed: '2.0.1',
     isInstalled: '2.0.1',
     notInstalled: false,
     packageWanted: '2.0.1',
     packageJson: '^2.0.1',
     isPrivate: undefined,
     devDependency: true,
     usedInScripts: undefined,
     mismatch: false,
     semverValidRange: '>=2.0.1 <3.0.0',
     semverValid: '2.0.1',
     easyUpgrade: true,
     bump: null,
     unused: true },
  webpack: 
   { moduleName: 'webpack',
     homepage: 'https://github.com/webpack/webpack',
     error: undefined,
     latest: '1.12.2',
     installed: '1.12.2',
     isInstalled: '1.12.2',
     notInstalled: false,
     packageWanted: '1.12.2',
     packageJson: '^1.9.11',
     isPrivate: undefined,
     devDependency: true,
     usedInScripts: undefined,
     mismatch: false,
     semverValidRange: '>=1.9.11 <2.0.0',
     semverValid: '1.12.2',
     easyUpgrade: true,
     bump: null,
     unused: false },
  'webpack-dev-middleware': 
   { moduleName: 'webpack-dev-middleware',
     homepage: 'http://github.com/webpack/webpack-dev-middleware',
     error: undefined,
     latest: '1.2.0',
     installed: '1.2.0',
     isInstalled: '1.2.0',
     notInstalled: false,
     packageWanted: '1.2.0',
     packageJson: '^1.2.0',
     isPrivate: undefined,
     devDependency: true,
     usedInScripts: undefined,
     mismatch: false,
     semverValidRange: '>=1.2.0 <2.0.0',
     semverValid: '1.2.0',
     easyUpgrade: true,
     bump: null,
     unused: false },
  'webpack-hot-middleware': 
   { moduleName: 'webpack-hot-middleware',
     homepage: 'https://github.com/glenjamin/webpack-hot-middleware#readme',
     error: undefined,
     latest: '2.4.1',
     installed: '2.4.1',
     isInstalled: '2.4.1',
     notInstalled: false,
     packageWanted: '2.4.1',
     packageJson: '^2.2.0',
     isPrivate: undefined,
     devDependency: true,
     usedInScripts: undefined,
     mismatch: false,
     semverValidRange: '>=2.2.0 <3.0.0',
     semverValid: '2.4.1',
     easyUpgrade: true,
     bump: null,
     unused: false } }

classnames                     😕  NOTUSED?  Possibly never referenced in the code.
                                            npm uninstall --save classnames to remove.

react                          😕  NOTUSED?  Possibly never referenced in the code.
                                            npm uninstall --save react to remove.

react-dom                      😕  NOTUSED?  Possibly never referenced in the code.
                                            npm uninstall --save react-dom to remove.

react-redux                    😕  NOTUSED?  Possibly never referenced in the code.
                                            npm uninstall --save react-redux to remove.

jsdom                          😎  MAJOR UP  Major update available: https://github.com/tmpvar/jsdom#readme
                                            npm install --save-dev jsdom@7.0.2 to go from 5.6.1 to 7.0.2

babel-plugin-react-transform   😕  NOTUSED?  Possibly never referenced in the code.
                                            npm uninstall --save-dev babel-plugin-react-transform to remove.

express                        😕  NOTUSED?  Possibly never referenced in the code.
                                            npm uninstall --save-dev express to remove.

babel-loader                   😕  NOTUSED?  Possibly never referenced in the code.
                                            npm uninstall --save-dev babel-loader to remove.

node-libs-browser              😕  NOTUSED?  Possibly never referenced in the code.
                                            npm uninstall --save-dev node-libs-browser to remove.

raw-loader                     😕  NOTUSED?  Possibly never referenced in the code.
                                            npm uninstall --save-dev raw-loader to remove.

react-addons-test-utils        😕  NOTUSED?  Possibly never referenced in the code.
                                            npm uninstall --save-dev react-addons-test-utils to remove.

react-transform-hmr            😕  NOTUSED?  Possibly never referenced in the code.
                                            npm uninstall --save-dev react-transform-hmr to remove.

style-loader                   😎  NEW VER!  NonSemver update available: https://github.com/webpack/style-loader#readme
                                            npm install --save-dev style-loader@0.13.0 to go from 0.12.4 to 0.13.0
                               😕  NOTUSED?  Possibly never referenced in the code.
                                            npm uninstall --save-dev style-loader to remove.

todomvc-app-css                😕  NOTUSED?  Possibly never referenced in the code.
                                            npm uninstall --save-dev todomvc-app-css to remove.

```

**Comment by js08** [comment] 2015-10-26 15:22
@dylang any luck :(

**Comment by js08** [comment] 2015-10-26 15:23
@dylang any luck :(

**Comment by js08** [comment] 2015-10-26 15:23
@dylang any luck :(

**Comment by js08** [comment] 2015-10-26 15:23
@dylang any luck :(

**Comment by lijunle** [comment] 2015-10-26 18:21
It fails, because of the JSX parser only enable on `.jsx` file in depcheck-es6. I will propose a fix for this.

*PS.* @js08 Please be polite! Everybody here has a full-time job and contribute code for free and fun. Please don't push and understand. Thank you very much!

**Comment by lijunle** [comment] 2015-10-26 18:23
Related: https://github.com/lijunle/depcheck-es6/issues/88

**Comment by js08** [comment] 2015-10-26 19:16
@lijunle hey by mistake it posted so many times :(

**Comment by lijunle** [comment] 2015-10-26 19:32
It is fixed via depcheck-es6 0.5.7. Please run uninstall and install npm-check to check.

```
lijunle@arch [03:01:29] [~/Downloads/redux-master/examples/todomvc] 
-> % ./node_modules/.bin/npm-check 

express                        😕  NOTUSED?  Possibly never referenced in the code.
                                            npm uninstall --save-dev express to remove.

babel-plugin-react-transform   😕  NOTUSED?  Possibly never referenced in the code.
                                            npm uninstall --save-dev babel-plugin-react-transform to remove.

babel-loader                   😕  NOTUSED?  Possibly never referenced in the code.
                                            npm uninstall --save-dev babel-loader to remove.

raw-loader                     😕  NOTUSED?  Possibly never referenced in the code.
                                            npm uninstall --save-dev raw-loader to remove.

node-libs-browser              😕  NOTUSED?  Possibly never referenced in the code.
                                            npm uninstall --save-dev node-libs-browser to remove.

jsdom                          😎  MAJOR UP  Major update available: https://github.com/tmpvar/jsdom#readme
                                            npm install --save-dev jsdom@7.0.2 to go from 5.6.1 to 7.0.2

react-transform-hmr            😕  NOTUSED?  Possibly never referenced in the code.
                                            npm uninstall --save-dev react-transform-hmr to remove.

style-loader                   😎  NEW VER!  NonSemver update available: https://github.com/webpack/style-loader#readme
                                            npm install --save-dev style-loader@0.13.0 to go from 0.12.4 to 0.13.0
                               😕  NOTUSED?  Possibly never referenced in the code.
                                            npm uninstall --save-dev style-loader to remove.

```

However, there are some remaining false alerts.

Packages | Comments
------------|----------------
express | Known issue, caused by the source itself. See https://github.com/lijunle/depcheck-es6/issues/91
babel-loader | Caused by webpack loader is not supported, see https://github.com/lijunle/depcheck-es6/issues/14
raw-loader | Same as above
style-loader | Save as above
babel-plugin-react-transform | Caused by `.babelrc` is not supported, ses https://github.com/lijunle/depcheck-es6/issues/97
react-transform-hmr | Same as above
[node-libs-browser](https://github.com/webpack/node-libs-browser) | I have no idea about how this package is used.

Because most of them are devDependencies false alert, I could keep them as low priority. Thanks for understanding.

**Comment by dylang** [comment] 2015-10-26 19:35
Thanks @lijunle! I'm going to close this as it's not something `npm-check` has control over.

**Closed by dylang** 2015-10-26 19:35 UTC

**Comment by js08** [comment] 2015-10-27 15:45
@dylang so you don't want to publish any latest version for npm-check package

**Comment by lijunle** [comment] 2015-10-27 15:54
@js08 npm-check does **not** need to publish a new version, you uninstall npm-check and re-install it is OK.

If you want to know why, refer to http://semver.org/

**Comment by js08** [comment] 2015-10-27 16:03
@lijunle I looked at this link  http://semver.org/ didn't understand much, can you give me short explaination

**Comment by js08** [comment] 2015-10-27 21:48
@dylang 

Hi,

depcheck-es6 does not recognise the following packages, will npm-check will be able to chyeck it

cookie-parser
blueimp-md5

require("http").createServer(function (req, res) {
    // The md5 module exports the md5() function: 
    var md5 = require("./md5").md5,
    // Use the following version if you installed the package with npm: 
    // var md5 = require("blueimp-md5").md5,

**Comment by dylang** [comment] 2015-10-27 22:31
@js08 If you can't take the time to learn essential parts of the technology you are using, please don't expect us to take time to provide you solutions to your problems. 

If that particular web site doesn't make sense, google around. There are many resources for learning what you need to learn.
