### ISSUE TITLE
Interactive npm-check uses `--save-dev` where it shouldn't

### ISSUE THREAD

**Issue by LinusU** [dylang/npm-check#94] opened 2016-03-23 08:47 UTC
Where `npm-check` without any flags only warns me that my local install is out of date, and suggest that I update it with `npm install _`, the interactive version will run it with the save flag and thus updates your package.json.

Example: I have version 6.1.1 of `got` installed locally and my package.json contains `^6.1.1`. This is the output from `npm-check`:

```text
got            😍  UPDATE!   Your local install is out of date. https://github.com/sindresorhus/got
                            npm install got to go from 6.1.1 to 6.2.0
```

But this is what happens when I run `npm-check -u`:

```text
? Choose which packages to update. got devDep  6.1.1  ❯  6.2.0  https://github.com/sindresorhus/got
Running npm install --color=always --save-dev got@6.2.0
my-module@0.0.0 /Users/linus/my-module
└── got@6.2.0 


[npm-check] Update complete!
[npm-check] You should re-run your tests to make sure everything works with the updates.
```

Notice the `--save-dev`.

This has led to dependency bumps commits which weren't necessary at all, but that serves to restrict the leeway that npm3 has to dedupe packages.

Would be very happy if this could be fixed :+1:

**Comment by dylang** [comment] 2016-03-30 01:09
Hi @LinusU, thanks for reporting this issue. 

Can you share your `package.json`? 

I'm pretty sure the only way `--save-dev` is included is for modules in `devDependencies`, but it can also happen if a dependency is in both `dependencies` and `devDependencies`.

**Comment by LinusU** [comment] 2016-03-30 19:31
The problem isn't that it's running `--save-dev` instead of `--save`, the dependency is in `devDependencies`.

The problem is that it's running `--save` or `--save-dev` even though it shouldn't modify the package.json at all...

**Comment by dylang** [comment] 2016-03-30 20:05
ahhh, that makes sense, thanks for the clarification!

I think there is more I'm not understanding, so thanks for your patience. 

When updating packages with `npm-check`, I assume everyone wants the `package.json` to match what they have installed, otherwise other users might not have the same versions of dependencies. 

In your example, you upgraded `got` to `6.2.0`.  
The `package.json` might have had `^6.1.1`, and `npm-check` would change it to `^6.2.0`. 
If my machine still had `got@6.1.1` it wouldn't be valid anymore, which is by design. 

> This has led to dependency bumps commits which weren't necessary at all, but that serves to restrict the leeway that npm3 has to dedupe packages.

I understand the flat installs of `npm@3`, but I don't understand how upgrading a dependency without changing the value in the `package.json` will make it easier to for npm to de-dupe.  

`npm@2` doesn't "re-ballance" sharing dependencies when individual packages are upgraded, so if several packages are sharing a single `got@6` install and you upgrade it to `got@7`, `npm` won't automatically install `got@6` for those dependencies. I haven't played with `npm@3` enough to see what it does.

Thanks for helping me understand the issues!

**Comment by dylang** [comment] 2016-03-30 20:10
I just realized you might be on an older version of `npm-check` with an issue that has since been fixed.

The bug had it show ALL modules that were installed for upgrade, not just those in your `package.json`. I had to change this behavior for `npm@3`. 

The current version is `4.1.4`, and I'm going to be releasing [5.0.0](https://github.com/dylang/npm-check/pull/96) once I can figure out Appveyor.

**Comment by LinusU** [comment] 2016-03-30 20:16
> The package.json might have had ^6.1.1, and npm-check would change it to ^6.2.0. 
If my machine still had got@6.1.1 it wouldn't be valid anymore, which is by design.

Hmm, that kind of makes sense, maybe instead the non-interactive output should be changed.

The bug really is about the inconsistency between `npm-check` and `npm-check -u`. If you don't supply the `-u` flag, npm-check will tell you to run `npm install got` not `npm install --save-dev got`.

**Comment by dylang** [comment] 2016-03-30 20:27
> The bug really is about the inconsistency between `npm-check` and `npm-check -u`. If you don't supply the `-u` flag, npm-check will tell you to run `npm install got` not `npm install --save-dev got`.

Yes! I see that bug too! This will be fixed in `npm-check@5`, hopefully today.

**Comment by LinusU** [comment] 2016-03-30 20:31
Nice :+1:

So is the solution to change the output of `npm-check` without the `-u`?

**Closed** 2016-03-30 22:26 UTC

**Comment by dylang** [comment] 2016-03-30 22:34
> So is the solution to change the output of `npm-check` without the `-u`?

Yup
