### ISSUE TITLE
Treatment of global modules' @next versions is inconsistent.

### ISSUE THREAD

**Issue by jaccarmac** [dylang/npm-check#95] opened 2016-03-25 04:14 UTC
I have two globally installed packages at their respective `@next` releases. Specifically, my `npm` is sitting at `3.8.5` and my `typescript` at `1.9.0-dev.20160324`.

`npm -g outdated` outputs pretty much what I've come to expect from installed prerelease packages.

```
npm -g outdated
Package                Current              Wanted  Latest  Location
npm                      3.8.5               3.8.5   3.8.3
typescript  1.9.0-dev.20160324  1.9.0-dev.20160324   1.8.9
```

However, `npm-check -g` only pays attention to `npm`, and suggests I downgrade. (`npm-check -gu` does exactly the same thing, but actually gives me a way to perform said downgrade.)

```
npm-check -g

npm   �  MINOR UP  Minor update available: https://docs.npmjs.com/
                   npm install --save npm@3.8.3 to go from 3.7.3 to 3.8.3

Use npm-check -u -g for interactive update.
```

`npm@3.7.3` is not even installed.

This behavior seems inconsistent to me. In a perfect world, I would expect `@next` versions to be recognized as newer than `@latest`. I'm used to the `npm outdated` behavior, where `@next` packages show up in the list of outdated packages but not in the same way as pure outdateds. In this case, I'm either doing something horribly wrong, `npm` metadata doesn't work the way I think it does, or there's a regression in the software.

On Windows 10 Insider Preview, using Node `5.9.0` and npm `3.8.5`, as mentioned above.

**Comment by dylang** [comment] 2016-03-28 02:05
Great suggestions @jaccarmac, thanks for providing helpful examples! I'll see what I can do.

**Comment by jaccarmac** [comment] 2016-04-03 03:45
Still doesn't seem to work for me, as of `5.0.3`.

**Comment by dylang** [comment] 2016-04-03 04:03
Thanks for the update. To be sure I'm trying to do the right behavior, can you tell me what is happening and what you are expecting to happen? Thanks!

**Comment by jaccarmac** [comment] 2016-04-03 04:12
Note this is on Windows, so there are technically two installs of `npm` somewhere.

All globally installed packages.

```
C:\Users\jaccarmac>npm -g ls --depth=0
C:\Users\jaccarmac\AppData\Roaming\npm
+-- bower@1.7.7
+-- gulp-cli@1.2.1
+-- http-server@0.9.0
+-- npm@3.8.6
+-- npm-check@5.0.3
+-- tern@0.18.0
+-- typescript@1.9.0-dev.20160402
`-- ungit@0.10.1
```

Output from doing outdated-checking the `npm` way.

```
C:\Users\jaccarmac>npm -g outdated
Package                Current              Wanted  Latest  Location
npm                      3.8.6               3.8.6   3.8.5
typescript  1.9.0-dev.20160402  1.9.0-dev.20160402   1.8.9
```

Output from doing outdated-checking with `npm-check`.

```
C:\Users\jaccarmac>npm-check -g

npm   �  PATCH UP  Patch update available. https://docs.npmjs.com/
                   npm install --save npm@3.8.5 to go from 3.8.3 to 3.8.5

Use npm-check -u -g for interactive update
```

I would expect that to not show the `npm` update, as I am in fact running `3.8.6`, where `3.8.6 > 3.8.5`.

```
C:\Users\jaccarmac>npm --version
3.8.6
```

Before, if `typescript` *were* out of date, `npm-check` would not tell me this. I'll see if that behavior persists after the next `typescript` update is ready.

**Comment by dylang** [comment] 2016-04-03 17:52
Hi @jaccarmac, thanks again for helping figure this out.

If it is finding the wrong location of your global modules in Windows then this is likely caused by https://github.com/jonschlinkert/global-prefix/issues/3. 

I'm going to close this ticket as we have it cover in #87. Let me know if you disagree that they are the same issue. Thanks!

**Closed by dylang** 2016-04-03 17:52 UTC
Labels: bug, help wanted

**Comment by jaccarmac** [comment] 2016-04-03 20:24
Looks like that is the cause of the issue with `npm`. However, it's still not suggesting updates to either itself or `typescript`.

**Comment by dylang** [comment] 2016-04-03 21:09
Can you use `npm-check -g --debug` and tell me what it says for `cwd` and `nodeModulesPath`.

You will need to scroll back up to find it, and it looks something like:

```
===============================
[npm-check] debug
current state { update: false,
  global: true,
  cwd: '/Users/dgreene/.nvm/versions/node/v4.2.1/lib/node_modules',
  nodeModulesPath: '/Users/dgreene/.nvm/versions/node/v4.2.1/lib/node_modules',
 ....cut...
```

**Comment by jaccarmac** [comment] 2016-04-04 04:57
```
...
cwd: 'C:\\Program Files\\nodejs\\node_modules',
nodeModulesPath: 'C:\\Program Files\\nodejs\\node_modules',
...
```

**Comment by dylang** [comment] 2016-04-04 15:10
Is what what you expect it to be?

I don't know if you have access to `which` or `where`, but if you are able to use either or something else can you figure out which directory these are running from:

* `npm`
* `npm-check`
* `tsc`
* as well as the result of `npm config get prefix`

My hope is that they are in same directory, and that location is where [global-prefix](https://github.com/jonschlinkert/global-prefix/issues/3) *should* be pointing to in Windows.

**Comment by jaccarmac** [comment] 2016-04-04 15:32
```
C:\Users\jaccarmac>where npm
C:\Program Files\nodejs\npm
C:\Program Files\nodejs\npm.cmd
C:\Users\jaccarmac\AppData\Roaming\npm\npm
C:\Users\jaccarmac\AppData\Roaming\npm\npm.cmd

C:\Users\jaccarmac>where npm-check
C:\Users\jaccarmac\AppData\Roaming\npm\npm-check
C:\Users\jaccarmac\AppData\Roaming\npm\npm-check.cmd

C:\Users\jaccarmac>where tsc
C:\Users\jaccarmac\AppData\Roaming\npm\tsc
C:\Users\jaccarmac\AppData\Roaming\npm\tsc.cmd

C:\Users\jaccarmac>npm --version
3.8.6
```

Interesting... Given that the `npm` version being reported is newer than the one that comes installed with Node globally, I assumed that the binary was also the newer one. Looks like, for whatever reason, an old version of the `npm` binary is reporting a newer version number. My best guess would be that I'm using an outdated script to start `npm` but all its `require`s are resolving to stuff in `AppData`.

```
C:\Users\jaccarmac>diff "C:\Program Files\nodejs"\npm C:\Users\jaccarmac\AppData\Roaming\npm\npm
1,34c1,15
< #!/bin/sh
< (set -o igncr) 2>/dev/null && set -o igncr; # cygwin encoding fix
<
< basedir=`dirname "$0"`
<
< case `uname` in
<     *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
< esac
<
< NODE_EXE="$basedir/node.exe"
< if ! [ -x "$NODE_EXE" ]; then
<   NODE_EXE=node
< fi
<
< NPM_CLI_JS="$basedir/node_modules/npm/bin/npm-cli.js"
<
< case `uname` in
<   *MINGW*)
<     NPM_PREFIX=`"$NODE_EXE" "$NPM_CLI_JS" prefix -g`
<     NPM_PREFIX_NPM_CLI_JS="$NPM_PREFIX/node_modules/npm/bin/npm-cli.js"
<     if [ -f "$NPM_PREFIX_NPM_CLI_JS" ]; then
<       NPM_CLI_JS="$NPM_PREFIX_NPM_CLI_JS"
<     fi
<     ;;
<   *CYGWIN*)
<     NPM_PREFIX=`"$NODE_EXE" "$NPM_CLI_JS" prefix -g`
<     NPM_PREFIX_NPM_CLI_JS="$NPM_PREFIX/node_modules/npm/bin/npm-cli.js"
<     if [ -f "$NPM_PREFIX_NPM_CLI_JS" ]; then
<       NPM_CLI_JS="$NPM_PREFIX_NPM_CLI_JS"
<     fi
<     ;;
< esac
<
< "$NODE_EXE" "$NPM_CLI_JS" "$@"
---
> #!/bin/sh
> basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
>
> case `uname` in
>     *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
> esac
>
> if [ -x "$basedir/node" ]; then
>   "$basedir/node"  "$basedir/node_modules/npm/bin/npm-cli.js" "$@"
>   ret=$?
> else
>   node  "$basedir/node_modules/npm/bin/npm-cli.js" "$@"
>   ret=$?
> fi
> exit $ret
```

```
C:\Users\jaccarmac>diff "C:\Program Files\nodejs"\npm.cmd C:\Users\jaccarmac\AppData\Roaming\npm\npm.cmd
1,19c1,7
< :: Created by npm, please don't edit manually.
< @ECHO OFF
<
< SETLOCAL
<
< SET "NODE_EXE=%~dp0\node.exe"
< IF NOT EXIST "%NODE_EXE%" (
<   SET "NODE_EXE=node"
< )
<
< SET "NPM_CLI_JS=%~dp0\node_modules\npm\bin\npm-cli.js"
< FOR /F "delims=" %%F IN ('CALL "%NODE_EXE%" "%NPM_CLI_JS%" prefix -g') DO (
<   SET "NPM_PREFIX_NPM_CLI_JS=%%F\node_modules\npm\bin\npm-cli.js"
< )
< IF EXIST "%NPM_PREFIX_NPM_CLI_JS%" (
<   SET "NPM_CLI_JS=%NPM_PREFIX_NPM_CLI_JS%"
< )
<
< "%NODE_EXE%" "%NPM_CLI_JS%" %*
---
> @IF EXIST "%~dp0\node.exe" (
>   "%~dp0\node.exe"  "%~dp0\node_modules\npm\bin\npm-cli.js" %*
> ) ELSE (
>   @SETLOCAL
>   @SET PATHEXT=%PATHEXT:;.JS;=;%
>   node  "%~dp0\node_modules\npm\bin\npm-cli.js" %*
> )
\ No newline at end of file
```

The binaries are significantly different as well. Didn't read them thoroughly yet, but is the global one selecting the newest version it can find? That would explain (some of) the weirdness.

**Comment by dylang** [comment] 2016-04-04 16:26
It will use the value of `npm config get prefix` to figure out where your global modules are. If that value is not set, I believe it will default to the parent of the working directory.

```
C:\Users\jaccarmac>where npm
C:\Program Files\nodejs\npm
C:\Program Files\nodejs\npm.cmd
C:\Users\jaccarmac\AppData\Roaming\npm\npm
C:\Users\jaccarmac\AppData\Roaming\npm\npm.cmd
```

This makes me wonder if something like `C:\Program Files\nodejs\` in your `PATH` before `C:\Users\jaccarmac\AppData\Roaming\npm`. Does that make sense?

**Comment by jaccarmac** [comment] 2016-04-04 16:35
Pretty sure that is the case. Specifically because `C:\Program Files` gets put in the global path, and `AppData` in the user path, where the effective runtime path is `global path + user path`.

**Comment by dylang** [comment] 2016-04-04 20:09
Do you think this something you need to fix with your system or is just how it works in Windows?

**Comment by jaccarmac** [comment] 2016-04-04 20:20
Hard to say. It's easy enough to fix, but the solution is dirty. Having to remove the global links to global programs just doesn't feel right.
