### ISSUE TITLE
Fatal error running npm-check command

### ISSUE THREAD

**Issue by leschirmeur** [dylang/npm-check#92] opened 2016-03-08 08:10 UTC
After installing npm-check (sudo npm install -g npm-check) and running it, I am getting the following error when running npm-check:

```
$ npm-check


#
# Fatal error in ../deps/v8/src/handles.h, line 48
# CHECK(location_ != NULL) failed
#

==== C stack trace ===============================

 1: ??
 2: ??
 3: ??
 4: ??
 5: ??
 6: ??
 7: ??
[1]    33663 illegal hardware instruction  npm-check
```

I have searched Google without any luck.

My node version is 0.12.7, my npm version is 2.11.3.

Any ideas what causes this error?

For reference, this is my package.json:
```
{
    "name": "x",
    "description": "x",
    "author": "x",
    "version": "1.2.4-dev",
    "dependencies": {},
    "devDependencies": {
        "better-console": "^0.2.4",
        "browser-sync": "^2.9.6",
        "chalk": "~1.1.1",
        "connect-livereload": "^0.5.3",
        "cordova-config-utils": "2.1.0",
        "del": "~1.1.1",
        "event-stream": "^3.3.1",
        "express": "^4.13.3",
        "glob": "^4.5.3",
        "gulp": "^3.9.0",
        "gulp-angular-filesort": "~1.1.1",
        "gulp-autoprefixer": "~2.3.1",
        "gulp-cached": "^1.1.0",
        "gulp-changed": "^1.3.0",
        "gulp-concat": "^2.6.0",
        "gulp-concat-css": "^2.2.0",
        "gulp-cordova-bump": "^1.3.0",
        "gulp-csso": "~1.0.1",
        "gulp-debug": "^2.1.0",
        "gulp-filter": "~2.0.2",
        "gulp-flatten": "~0.2.0",
        "gulp-footer": "^1.0.5",
        "gulp-header": "^1.7.1",
        "gulp-help": "^1.6.1",
        "gulp-iconfont": "^4.0.2",
        "gulp-iconfont-css": "1.0.1",
        "gulp-if": "^1.2.5",
        "gulp-imagemin": "~2.3.0",
        "gulp-inject": "~2.2.0",
        "gulp-jscs": "^2.0.0",
        "gulp-jscs-stylish": "^1.1.2",
        "gulp-jsdoc": "^0.1.4",
        "gulp-jshint": "~1.11.2",
        "gulp-karma": "~0.0.4",
        "gulp-less": "^3.0.5",
        "gulp-livereload": "^3.8.0",
        "gulp-load-plugins": "~0.8.1",
        "gulp-minify-css": "^1.2.4",
        "gulp-minify-html": "~1.0.4",
        "gulp-ng-annotate": "~1.1.0",
        "gulp-ng-constant": "^1.1.0",
        "gulp-ngdocs": "^0.2.13",
        "gulp-plumber": "^1.0.1",
        "gulp-po2json-angular-translate": "0.0.1",
        "gulp-protractor": "~1.0.0",
        "gulp-remember": "^0.3.0",
        "gulp-rename": "^1.2.2",
        "gulp-replace": "~0.5.4",
        "gulp-rev": "~6.0.1",
        "gulp-rev-replace": "~0.4.2",
        "gulp-sass": "^2.2.0",
        "gulp-scss-lint": "^0.3.9",
        "gulp-shell": "^0.4.3",
        "gulp-size": "~2.0.0",
        "gulp-sort": "^1.1.1",
        "gulp-sourcemaps": "^1.5.2",
        "gulp-strip-css-comments": "^1.2.0",
        "gulp-strip-debug": "^1.0.2",
        "gulp-task-listing": "^1.0.1",
        "gulp-uglify": "~1.4.2",
        "gulp-useref": "~1.3.0",
        "gulp-util": "^3.0.6",
        "http-proxy": "~1.11.2",
        "jasmine-core": "2.3.4",
        "js-string-escape": "^1.0.0",
        "jshint-stylish": "~2.0.1",
        "karma": "0.13.10",
        "karma-jasmine": "0.3.6",
        "karma-phantomjs-launcher": "0.2.1",
        "lodash": "^3.10.1",
        "lodash._basecopy": "latest",
        "main-bower-files": "~2.9.0",
        "merge-stream": "^1.0.0",
        "node-sass": "^3.4.2",
        "open": "0.0.5",
        "path": "^0.12.7",
        "phantomjs": "1.9.18",
        "protractor": "2.2.0",
        "request": "~2.63.0",
        "ripple-emulator": "^0.9.32",
        "run-sequence": "^1.1.4",
        "shelljs": "^0.5.3",
        "stream-series": "^0.1.1",
        "streamqueue": "^1.1.1",
        "uglify-save-license": "^0.4.1",
        "wiredep": "~2.2.2",
        "yargs": "^3.25.0"
    },
    "engines": {
        "node": ">=0.12.7"
    },
    "cordovaPlugins": [
        "ionic-plugin-keyboard@1.0.8",
        "com.verso.cordova.clipboard@0.1.0",
        "cordova-plugin-calendar@4.4.7",
        "cordova-plugin-console@1.0.2",
        "cordova-plugin-contacts@2.0.1",
        "cordova-plugin-datepicker@0.9.2",
        "cordova-plugin-device@1.1.1",
        "cordova-plugin-dialogs@1.2.0",
        "cordova-plugin-file@4.1.1",
        "cordova-plugin-file-transfer@1.5.0",
        "cordova-plugin-geolocation@2.1.0",
        "cordova-plugin-globalization@1.0.2",
        "cordova-plugin-inappbrowser@1.2.0",
        "cordova-plugin-media@2.2.0",
        "cordova-plugin-network-information@1.2.0",
        "cordova-plugin-splashscreen@3.2.0",
        "cordova-plugin-statusbar@2.1.1",
        "cordova-plugin-vibration@2.1.0",
        "cordova-plugin-whitelist@1.2.1",
        "de.appplant.cordova.common.registerusernotificationsettings@1.0.1",
        "de.appplant.cordova.plugin.badge@0.7.1",
        "cordova-plugin-x-socialsharing@5.0.10",
        {
          "locator": "https://github.com/apache/cordova-plugin-camera.git#f792aaacc3e844f3e973c124f0ec4a76bbbd1c47",
          "id": "cordova-plugin-camera"
        },
        {
            "locator": "https://github.com/EddyVerbruggen/LaunchMyApp-PhoneGap-Plugin.git",
            "id": "nl.x-services.plugins.launchmyapp@4.1.3",
            "variables": {
                "URL_SCHEME": "quiplyapp"
            }
        },
        {
            "locator": "https://github.com/JonathanAquino/cordova-last-photo-taken.git",
            "id": "com.ning.last-photo-taken@0.0.2"
        },
        {
            "locator": "https://github.com/protonet/cordova-plugin-image-resizer.git",
            "id": "cordova-plugin-image-resizer@0.1.1"
        },
        {
            "locator": "https://github.com/phonegap-build/PushPlugin.git",
            "id": "com.phonegap.plugins.PushPlugin@2.5.0"
        },
        {
            "locator": "https://github.com/katzer/cordova-plugin-email-composer.git",
            "id": "de.appplant.cordova.plugin.email-composer@0.8.2"
        },
        {
            "locator": "https://github.com/whiteoctober/cordova-plugin-app-version.git",
            "id": "uk.co.whiteoctober.cordova.appversion@0.1.8"
        },
        {
            "locator": "https://github.com/pushandplay/cordova-plugin-apprate.git",
            "id": "org.pushandplay.cordova.apprate@1.1.9"
        },
        "cordova-plugin-crosswalk-webview@1.5.0"
    ],
    "cordovaPlatforms": [
        "browser",
        {
            "platform": "android",
            "version": "5.1.0",
            "locator": "android@5.1.0"
        },
        "ios"
    ]
}
```

**Comment by dylang** [comment] 2016-03-30 01:20
Hi @leschirmeur, I can't reproduce this problem. It's very strange, I don't use any native modules, so this sounds like an issue with the version of Node you are using. 

I am unfortunately stopping support for Node 0.x.z with the next release and will only test and support node 4 and newer, so I am closing this issue.

Hope you are able to figure something out.

**Closed by dylang** 2016-03-30 01:20 UTC

**Comment by leschirmeur** [comment] 2016-03-30 10:40
Hi @dylang, no worries, still does not work for me but just won't use npm-check for the time being then.
