### ISSUE TITLE
some used packages are listed as not used

### ISSUE THREAD

**Issue by juancabrera** [dylang/npm-check#15] opened 2015-03-09 19:49 UTC
As an example. When I run ```npm-check``` on my current project I got this:
![screen shot 2015-03-09 at 3 40 09 pm](https://cloud.githubusercontent.com/assets/355253/6562867/c9826674-c672-11e4-83db-cdcf657c422e.png)

It's saying that ```fluxible-plugin-routr``` is not being used but actually it's being used on app.js (root level):
```javascript
import React        from 'react';
import FluxibleApp  from 'fluxible';
import routrPlugin  from 'fluxible-plugin-routr';

var app = new FluxibleApp({
  appComponent: React.createFactory(require('./components/Application.jsx'))
});

// setup routes
app.plug(routrPlugin({ routes: require('./configs/routes') }));

// setup stores
app.registerStore(require('./stores/ApplicationStore'));

module.exports = app;
```
The same is happening with other packages too.

**Comment by jameswomack** [comment] 2015-03-16 14:31
@juancabrera Have you noticed that it doesn't recognize any modules imported in JSX files?

**Comment by jameswomack** [comment] 2015-03-16 14:34
@juancabrera This module uses https://github.com/rumpl/depcheck to actually find dependencies—you might want to look there

**Comment by dylang** [comment] 2015-03-16 15:11
@juancabrera @jameswomack Correct about depcheck. Depcheck uses https://www.npmjs.com/package/detective to find all `require` statements. Is there something similar for jsx `import from` syntax?

**Comment by jameswomack** [comment] 2015-03-16 15:38
@dylang Not sure. Transpilation is the only method I know off the top of my head.

**Comment by tacomanator** [comment] 2015-04-26 04:27
It's not just JSX. A few more cases that I've run into include modules required in LiveScript files and modules used as browserify transforms in package.json.

It would be great if there was an option to not check if packages are used or not.

**Comment by dylang** [comment] 2015-04-26 18:16
> It would be great if there was an option to not check if packages are used or not.

Good news, there is:

> -s, --skip-unused  Skip check for unused packages.

See `--help` for other options.

**Comment by tacomanator** [comment] 2015-04-26 18:20
@dylang I may have messed up but I tried that option and it didn't show me newer packages available for modules it detected as unused. Was I mistaken and it actually does show updates for packages even if they are unused when using that option?

**Comment by dylang** [comment] 2015-04-26 18:44
@tacomanator It just skips the *check* for unused modules, it still will tell you if *any* of your modules are outdated.

**Comment by tacomanator** [comment] 2015-04-26 18:45
Ok then I must have made a mistake while using it. Thanks @dylang

**Comment by dylang** [comment] 2015-08-29 23:20
Once we get https://github.com/rumpl/depcheck/pull/29 merged in we should have support for ES6 `import` statements.

I'm going to close this as  a duplicate of #17.

**Closed by dylang** 2015-08-29 23:20 UTC
